### ISSUE TITLE
FastTextView Issue

### ISSUE THREAD

**Issue by TechAngel85** [MetaIdea/nms-amumss-lua-mod-script-collection#51]
[Fast Text View](https://github.com/MetaIdea/nms-amumss-lua-mod-script-collection/blob/main/Babscoole/_FastTextView.lua) is reporting with the following:

.>>> 'Starting to process script' #43/58 [_FastTextView.lua] at 164.964 sec (2:44)

.>>> Opening User Lua Script, Please wait...

   @@@ ********** Analysing script... **********

   @@@ Checking script using LUAC...
   @@@ Done without problem

   @@@ Scanning script for container...
       > CONTAINER found at lines 1-38 (found 15 {} pairs)
       > CONTAINER will be further analyzed...
   @@@ Done

   @@@ Basic Syntax Analysis...
   @@@ Detected these other syntax problems, see also TOOLS\ModScriptCheck folder...
       > line 3, col 48: "notice[undefined_variable]: `Version` is not defined"
   @@@ Done

   @@@ ********** All done in 0.048 sec **********

.>>> Loading script...

vvvvvvvv Running script internal code...
 Lua Script error: [string "User Script"]:7: attempt to concatenate a nil value (global 'Version') 
                        line number above ^ refers to TOOLS\ModScriptCheck\_FastTextView.RawScript.lua 
    ^^^^^^^^ Done running script internal code in 0.020 sec

XXXXX Error loading USER script! XXXXX 

.>>>  [ERROR] NMS_MOD_DEFINITION_CONTAINER is not a valid table or is empty, this script has a problem!

**Comment by Babscoole** [comment]
Corrected.  BTW, there is no support here for the repo, as it's scripts from every author, including those gone for years.  Much better off coming to the modding discord for help with a script
