### ISSUE TITLE
Bug Increased Stack Size.lua

### ISSUE THREAD

**Issue by cropots** [MetaIdea/nms-amumss-lua-mod-script-collection#54]
I just completely lost the fun of playing on my current save, I found a serious problem in this mod "Increased Stack Size.lua", when using an ant-materia refiner, it will automatically create thousands of ant-materia without stopping. I disabled the mod and found that it is causing the problem.

**Comment by Babscoole** [comment]
You need to leave POST on the mod page on NexusMods for the mod author, JamesDude420.  It is his responsibility to update or change the mod if it is broken.  Last updated for NMS 4.50, so guessing he's abandoned.  This is just a repository of all NMS Lua scripts.  When mods and Luas are updated or changed by the authors, the updated are put into the repo, but if abandoned, they will no longer be maintained.

**Comment by cropots** [comment]
Thanks!
