### ISSUE TITLE
Can't merge anything with Winder_GalaxySFlightUltra.lua

### ISSUE THREAD

**Issue by Yashirow** [MetaIdea/nms-amumss-lua-mod-script-collection#55]
Title. I know how to do basic merges with AMUMSS but this lua is *weird* for me. Can't merge it with anything that edit `GCSPACESHIPGLOBALS.GLOBAL.MBIN` since every time it create a compatibility patch. Is there a workaround to merge it easily with other mods that edit `GCSPACESHIPGLOBALS.GLOBAL.MBIN` ? Thanks !

**Comment by Babscoole** [comment]
This is just a collection of scripts by hundreds of different authors.  There's no support here.  Try the mod page on nexusmods or an nms discord
